export enum PublisherCredibilityLevel {
  HIGH = 'HIGH',
  MODERATE = 'MODERATE',
  LOW = 'LOW',
  UNKNOWN = 'UNKNOWN',
  INSUFFICIENT_INFORMATION = 'INSUFFICIENT_INFORMATION',
}

export enum PublisherReviewStatus {
  UNREVIEWED = 'UNREVIEWED',
  AUTOMATED_REVIEW = 'AUTOMATED_REVIEW',
  MANUALLY_REVIEWED = 'MANUALLY_REVIEWED',
}
