export enum DailyChallengeTopic {
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  ELECTIONS = 'ELECTIONS',
  CLIMATE_WEATHER = 'CLIMATE_WEATHER',
  EDUCATION = 'EDUCATION',
  MONEY_SCAMS = 'MONEY_SCAMS',
  IMAGES_VIDEO = 'IMAGES_VIDEO',
  SCIENCE_TECHNOLOGY = 'SCIENCE_TECHNOLOGY',
  JOBS_RECRUITMENT = 'JOBS_RECRUITMENT',
  SCHOLARSHIPS = 'SCHOLARSHIPS',
  BANKING_FINANCE = 'BANKING_FINANCE',
  SECURITY_ALERTS = 'SECURITY_ALERTS',
  AI_GENERATED_CONTENT = 'AI_GENERATED_CONTENT',
  GOVERNMENT_NOTICES = 'GOVERNMENT_NOTICES',
  SOCIAL_MEDIA_RUMOURS = 'SOCIAL_MEDIA_RUMOURS',
  VOICE_NOTES = 'VOICE_NOTES',
  NEWS_HEADLINES = 'NEWS_HEADLINES',
  STATISTICS_AND_NUMBERS = 'STATISTICS_AND_NUMBERS',
  CELEBRITY_INFORMATION = 'CELEBRITY_INFORMATION',
}

export enum DailyChallengeCompetency {
  CLAIM_IDENTIFICATION = 'CLAIM_IDENTIFICATION',
  SOURCE_IDENTIFICATION = 'SOURCE_IDENTIFICATION',
  SOURCE_CREDIBILITY = 'SOURCE_CREDIBILITY',
  SOURCE_INDEPENDENCE = 'SOURCE_INDEPENDENCE',
  DATE_AND_RECENCY = 'DATE_AND_RECENCY',
  EVIDENCE_EVALUATION = 'EVIDENCE_EVALUATION',
  CONTEXT_RECOGNITION = 'CONTEXT_RECOGNITION',
  MANIPULATION_RECOGNITION = 'MANIPULATION_RECOGNITION',
  RESPONSIBLE_SHARING = 'RESPONSIBLE_SHARING',
  VISUAL_VERIFICATION = 'VISUAL_VERIFICATION',
  AUDIO_VIDEO_CAUTION = 'AUDIO_VIDEO_CAUTION',
  AI_CONTENT_CAUTION = 'AI_CONTENT_CAUTION',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
}

export enum ChallengeGenerationMode {
  AI = 'AI',
  TEMPLATE = 'TEMPLATE',
  MANUAL = 'MANUAL',
  LEGACY = 'LEGACY',
}

export enum ChallengeGenerationValidationStatus {
  PASSED = 'PASSED',
  LEGACY = 'LEGACY',
}
