export enum MediaAnalysisStatus {
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  UNAVAILABLE = 'UNAVAILABLE',
  FAILED = 'FAILED',
}

export enum AiContentIndicator {
  LOW_INDICATION = 'LOW_INDICATION',
  MODERATE_INDICATION = 'MODERATE_INDICATION',
  HIGH_INDICATION = 'HIGH_INDICATION',
  INCONCLUSIVE = 'INCONCLUSIVE',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum ReverseImageStatus {
  COMPLETE = 'COMPLETE',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  UNAVAILABLE = 'UNAVAILABLE',
}

export enum TranscriptStatus {
  COMPLETE = 'COMPLETE',
  PARTIAL = 'PARTIAL',
  UNAVAILABLE = 'UNAVAILABLE',
  FAILED = 'FAILED',
}
