export enum ClaimVerdict {
  SUPPORTED = 'SUPPORTED',
  MOSTLY_SUPPORTED = 'MOSTLY_SUPPORTED',
  MIXED = 'MIXED',
  MISLEADING = 'MISLEADING',
  CONTRADICTED = 'CONTRADICTED',
  UNSUPPORTED = 'UNSUPPORTED',
  OUTDATED = 'OUTDATED',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
  UNVERIFIABLE = 'UNVERIFIABLE',
}

export enum AnalysisSeverity {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
}

export enum ManipulationCategory {
  ARTIFICIAL_URGENCY = 'ARTIFICIAL_URGENCY',
  FEAR = 'FEAR',
  ANGER = 'ANGER',
  FALSE_AUTHORITY = 'FALSE_AUTHORITY',
  SOCIAL_PRESSURE = 'SOCIAL_PRESSURE',
  CONSPIRACY_FRAMING = 'CONSPIRACY_FRAMING',
  ABSOLUTIST_LANGUAGE = 'ABSOLUTIST_LANGUAGE',
  EMOTIONAL_BLACKMAIL = 'EMOTIONAL_BLACKMAIL',
  SCARCITY = 'SCARCITY',
  US_VS_THEM = 'US_VS_THEM',
  UNVERIFIED_EXCLUSIVITY = 'UNVERIFIED_EXCLUSIVITY',
  CALL_TO_VIRALITY = 'CALL_TO_VIRALITY',
}

export enum MissingContextType {
  OLD_CONTENT_PRESENTED_AS_CURRENT = 'OLD_CONTENT_PRESENTED_AS_CURRENT',
  LOCATION_OMITTED = 'LOCATION_OMITTED',
  DATE_OMITTED = 'DATE_OMITTED',
  QUOTE_TRUNCATED = 'QUOTE_TRUNCATED',
  PROPOSAL_PRESENTED_AS_LAW = 'PROPOSAL_PRESENTED_AS_LAW',
  CORRELATION_PRESENTED_AS_CAUSATION = 'CORRELATION_PRESENTED_AS_CAUSATION',
  STATISTIC_WITHOUT_BASELINE = 'STATISTIC_WITHOUT_BASELINE',
  STATISTIC_WITHOUT_SAMPLE_SIZE = 'STATISTIC_WITHOUT_SAMPLE_SIZE',
  CHERRY_PICKED_TIMEFRAME = 'CHERRY_PICKED_TIMEFRAME',
  ORIGINAL_CAPTION_REMOVED = 'ORIGINAL_CAPTION_REMOVED',
  CONDITIONS_OMITTED = 'CONDITIONS_OMITTED',
  EXCEPTION_OMITTED = 'EXCEPTION_OMITTED',
  SOURCE_OMITTED = 'SOURCE_OMITTED',
  UNCERTAINTY_OMITTED = 'UNCERTAINTY_OMITTED',
}

export enum OverallVerdict {
  SUPPORTED = 'SUPPORTED',
  MOSTLY_SUPPORTED = 'MOSTLY_SUPPORTED',
  MIXED = 'MIXED',
  MISLEADING = 'MISLEADING',
  CONTRADICTED = 'CONTRADICTED',
  UNSUPPORTED = 'UNSUPPORTED',
  OUTDATED = 'OUTDATED',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
}

export enum RiskLevel {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
  UNKNOWN = 'UNKNOWN',
}

export enum BiasMetricName {
  EMOTIONAL_INTENSITY = 'EMOTIONAL_INTENSITY',
  SENSATIONALISM = 'SENSATIONALISM',
  NEUTRALITY = 'NEUTRALITY',
  EVIDENCE_BALANCE = 'EVIDENCE_BALANCE',
  HEADLINE_ALIGNMENT = 'HEADLINE_ALIGNMENT',
  LOADED_LANGUAGE = 'LOADED_LANGUAGE',
  CERTAINTY_INFLATION = 'CERTAINTY_INFLATION',
}
