export enum MissionStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}
export enum MissionDifficulty {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}
export enum AssessmentPhase {
  BASELINE = 'BASELINE',
  FOLLOW_UP = 'FOLLOW_UP',
}
export enum MissionQuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  SCENARIO_CLASSIFICATION = 'SCENARIO_CLASSIFICATION',
  SOURCE_COMPARISON = 'SOURCE_COMPARISON',
  CLAIM_IDENTIFICATION = 'CLAIM_IDENTIFICATION',
  RESPONSIBLE_SHARING = 'RESPONSIBLE_SHARING',
  CONFIDENCE_RATING = 'CONFIDENCE_RATING',
}
export enum MissionParticipantStatus {
  JOINED = 'JOINED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}
