export enum AssetStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  ATTACHED = 'ATTACHED',
  QUARANTINED = 'QUARANTINED',
  DELETION_PENDING = 'DELETION_PENDING',
  DELETED = 'DELETED',
  FAILED = 'FAILED',
}
