export enum ClaimType {
  EVENT = 'EVENT',
  POLICY = 'POLICY',
  LAW = 'LAW',
  STATISTIC = 'STATISTIC',
  QUOTE = 'QUOTE',
  HEALTH = 'HEALTH',
  SCIENCE = 'SCIENCE',
  FINANCE = 'FINANCE',
  PUBLIC_SAFETY = 'PUBLIC_SAFETY',
  IDENTITY = 'IDENTITY',
  LOCATION = 'LOCATION',
  HISTORICAL = 'HISTORICAL',
  OTHER = 'OTHER',
}

export enum ClaimImportance {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum ClaimVerifiability {
  VERIFIABLE = 'VERIFIABLE',
  PARTIALLY_VERIFIABLE = 'PARTIALLY_VERIFIABLE',
  OPINION = 'OPINION',
  PREDICTION = 'PREDICTION',
  VALUE_JUDGMENT = 'VALUE_JUDGMENT',
  INSUFFICIENT_CONTEXT = 'INSUFFICIENT_CONTEXT',
}

export enum ClaimTimeSensitivity {
  CURRENT = 'CURRENT',
  RECENT = 'RECENT',
  HISTORICAL = 'HISTORICAL',
  TIMELESS = 'TIMELESS',
  UNKNOWN = 'UNKNOWN',
}

export enum SearchQueryCategory {
  OFFICIAL = 'OFFICIAL',
  SUPPORTING = 'SUPPORTING',
  CONTRADICTING = 'CONTRADICTING',
  CONTEXTUAL = 'CONTEXTUAL',
  RECENCY_CHECK = 'RECENCY_CHECK',
  ORIGINAL_SOURCE = 'ORIGINAL_SOURCE',
  QUOTE_SOURCE = 'QUOTE_SOURCE',
  IMAGE_CONTEXT = 'IMAGE_CONTEXT',
}
