export enum UrlExtractionState {
  EXTRACTED = 'EXTRACTED',
  PARTIALLY_EXTRACTED = 'PARTIALLY_EXTRACTED',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',
  PAYWALLED = 'PAYWALLED',
  BLOCKED = 'BLOCKED',
  UNSUPPORTED = 'UNSUPPORTED',
  NOT_FOUND = 'NOT_FOUND',
  TIMEOUT = 'TIMEOUT',
  UNSAFE_URL = 'UNSAFE_URL',
}
