import {
  BadgeAvailability,
  BadgeCriteriaType,
} from '../enums/gamification.enum';

export const FIXED_BADGE_CATALOG = [
  {
    code: 'FIRST_CHECK',
    name: 'First Check',
    slug: 'first-check',
    description: 'Completed your first Verith investigation.',
    whyItMatters:
      'Checking before sharing is the foundation of evidence-informed action.',
    category: 'INVESTIGATION',
    iconKey: 'first-check',
    criteriaType: BadgeCriteriaType.VERIFICATION_COUNT,
    criteria: { threshold: 1 },
    rarity: 'FOUNDATIONAL',
    reward: { xp: 25, truthPoints: 10 },
    sortOrder: 10,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'EVIDENCE_HUNTER',
    name: 'Evidence Hunter',
    slug: 'evidence-hunter',
    description: 'Inspected 10 distinct evidence sources in completed reports.',
    whyItMatters:
      'Opening the evidence helps you judge support instead of trusting a verdict alone.',
    category: 'EVIDENCE',
    iconKey: 'evidence-hunter',
    criteriaType: BadgeCriteriaType.EVIDENCE_INSPECTION_COUNT,
    criteria: { threshold: 10 },
    rarity: 'SKILLED',
    reward: { xp: 50, truthPoints: 20 },
    sortOrder: 20,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'CONTEXT_DETECTIVE',
    name: 'Context Detective',
    slug: 'context-detective',
    description: 'Completed 3 context-focused learning or practice activities.',
    whyItMatters:
      'Dates, framing, and omitted details can change what a claim appears to mean.',
    category: 'LEARNING',
    iconKey: 'context-detective',
    criteriaType: BadgeCriteriaType.TAGGED_ACTIVITY_COUNT,
    criteria: { threshold: 3, tags: ['context'] },
    rarity: 'SKILLED',
    reward: { xp: 40, truthPoints: 15 },
    sortOrder: 30,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'MANIPULATION_SPOTTER',
    name: 'Manipulation Spotter',
    slug: 'manipulation-spotter',
    description:
      'Completed 3 manipulation-recognition learning or practice activities.',
    whyItMatters:
      'Recognising emotional and visual manipulation creates space for careful judgment.',
    category: 'LEARNING',
    iconKey: 'manipulation-spotter',
    criteriaType: BadgeCriteriaType.TAGGED_ACTIVITY_COUNT,
    criteria: { threshold: 3, tags: ['manipulation', 'visual-verification'] },
    rarity: 'SKILLED',
    reward: { xp: 40, truthPoints: 15 },
    sortOrder: 40,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'SOURCE_SLEUTH',
    name: 'Source Sleuth',
    slug: 'source-sleuth',
    description:
      'Completed 5 source-evaluation learning or practice activities.',
    whyItMatters:
      'Source quality, independence, and proximity shape the strength of evidence.',
    category: 'EVIDENCE',
    iconKey: 'source-sleuth',
    criteriaType: BadgeCriteriaType.TAGGED_ACTIVITY_COUNT,
    criteria: { threshold: 5, tags: ['source-checking', 'evidence'] },
    rarity: 'ADVANCED',
    reward: { xp: 60, truthPoints: 25 },
    sortOrder: 50,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'GUIDED_INVESTIGATOR',
    name: 'Guided Investigator',
    slug: 'guided-investigator',
    description: 'Completed 5 guided investigations.',
    whyItMatters:
      'Participating in the reasoning builds skills that transfer beyond one report.',
    category: 'GUIDED',
    iconKey: 'guided-investigator',
    criteriaType: BadgeCriteriaType.GUIDED_INVESTIGATION_COUNT,
    criteria: { threshold: 5 },
    rarity: 'ADVANCED',
    reward: { xp: 75, truthPoints: 30 },
    sortOrder: 60,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'CHALLENGE_MASTER',
    name: 'Challenge Master',
    slug: 'challenge-master',
    description: 'Passed 10 distinct Verith challenges.',
    whyItMatters:
      'Repeated practice turns careful verification into a dependable habit.',
    category: 'LEARNING',
    iconKey: 'challenge-master',
    criteriaType: BadgeCriteriaType.CHALLENGE_STREAK,
    criteria: { threshold: 10 },
    rarity: 'ADVANCED',
    reward: { xp: 75, truthPoints: 30 },
    sortOrder: 70,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'COMMUNITY_CONTRIBUTOR',
    name: 'Community Contributor',
    slug: 'community-contributor',
    description: 'Completed a community verification mission.',
    whyItMatters:
      'Media literacy grows when evidence-informed action reaches a community.',
    category: 'COMMUNITY',
    iconKey: 'community-contributor',
    criteriaType: BadgeCriteriaType.MISSION_COUNT,
    criteria: { threshold: 1 },
    rarity: 'COMMUNITY',
    reward: { xp: 50, truthPoints: 20 },
    sortOrder: 80,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'STREAK_7',
    name: '7-Day Streak',
    slug: 'streak-7',
    description: 'Maintained a seven-day learning streak.',
    whyItMatters: 'Consistent small actions build durable verification habits.',
    category: 'STREAK',
    iconKey: 'streak-7',
    criteriaType: BadgeCriteriaType.DAILY_STREAK,
    criteria: { threshold: 7 },
    rarity: 'CONSISTENT',
    reward: { xp: 50, truthPoints: 20 },
    sortOrder: 90,
    availability: BadgeAvailability.AVAILABLE,
  },
  {
    code: 'STREAK_30',
    name: '30-Day Streak',
    slug: 'streak-30',
    description: 'Maintained a thirty-day learning streak.',
    whyItMatters:
      'A month of consistent practice demonstrates sustained commitment.',
    category: 'STREAK',
    iconKey: 'streak-30',
    criteriaType: BadgeCriteriaType.DAILY_STREAK,
    criteria: { threshold: 30 },
    rarity: 'EXCEPTIONAL',
    reward: { xp: 150, truthPoints: 60 },
    sortOrder: 100,
    availability: BadgeAvailability.AVAILABLE,
  },
] as const;
