import { Injectable, Logger } from '@nestjs/common';
import { EventEmitter2 } from '@nestjs/event-emitter';
import { Interval } from '@nestjs/schedule';
import { InjectModel } from '@nestjs/mongoose';
import type { Model } from 'mongoose';
import {
  DomainEventOutboxRecord,
  type DomainEventOutboxDocument,
} from './domain-event.schema';
import { DomainEventStatus } from './domain-event-status.enum';

@Injectable()
export class DomainEventDispatcher {
  private static readonly BATCH_SIZE = 50;
  private static readonly LOCK_MS = 30000;
  private static readonly MAX_ATTEMPTS = 10;
  private static readonly RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
  private readonly logger = new Logger(DomainEventDispatcher.name);
  private dispatching = false;

  constructor(
    @InjectModel(DomainEventOutboxRecord.name)
    private readonly events: Model<DomainEventOutboxRecord>,
    private readonly emitter: EventEmitter2,
  ) {}

  // Five seconds keeps user-facing side effects prompt while removing 80% of
  // the idle MongoDB polling generated by the former one-second relay.
  @Interval('domain-event-outbox-relay', 5000)
  async dispatchPending(): Promise<void> {
    if (this.dispatching) return;
    this.dispatching = true;
    try {
      for (
        let index = 0;
        index < DomainEventDispatcher.BATCH_SIZE;
        index += 1
      ) {
        const event = await this.claimNext();
        if (!event) break;
        await this.dispatch(event);
      }
    } finally {
      this.dispatching = false;
    }
  }

  private claimNext(): Promise<DomainEventOutboxDocument | null> {
    const now = new Date();
    return this.events
      .findOneAndUpdate(
        {
          $or: [
            {
              status: {
                $in: [DomainEventStatus.PENDING, DomainEventStatus.FAILED],
              },
              availableAt: { $lte: now },
            },
            {
              status: DomainEventStatus.PROCESSING,
              lockedUntil: { $lte: now },
            },
          ],
        },
        {
          $set: {
            status: DomainEventStatus.PROCESSING,
            lockedUntil: new Date(
              now.getTime() + DomainEventDispatcher.LOCK_MS,
            ),
          },
        },
        {
          sort: { occurredAt: 1 },
          returnDocument: 'after',
        },
      )
      .exec();
  }

  private async dispatch(event: DomainEventOutboxDocument): Promise<void> {
    try {
      if (!this.emitter.listenerCount(event.name)) {
        throw new Error('DOMAIN_EVENT_HANDLER_NOT_REGISTERED');
      }
      await this.emitter.emitAsync(event.name, {
        id: event.eventId,
        name: event.name,
        version: 1,
        aggregateType: event.aggregateType,
        aggregateId: event.aggregateId,
        correlationId: event.correlationId,
        occurredAt: event.occurredAt,
        payload: event.payload,
      });
      const publishedAt = new Date();
      await this.events.updateOne(
        { _id: event._id, status: DomainEventStatus.PROCESSING },
        {
          $set: {
            status: DomainEventStatus.PUBLISHED,
            publishedAt,
            expiresAt: new Date(
              publishedAt.getTime() + DomainEventDispatcher.RETENTION_MS,
            ),
          },
          $unset: {
            lockedUntil: 1,
            lastFailureCode: 1,
          },
        },
      );
    } catch (error) {
      const attempts = event.attempts + 1;
      const deadLetter = attempts >= DomainEventDispatcher.MAX_ATTEMPTS;
      const failureCode =
        error instanceof Error &&
        error.message === 'DOMAIN_EVENT_HANDLER_NOT_REGISTERED'
          ? error.message
          : 'DOMAIN_EVENT_HANDLER_FAILED';
      await this.events.updateOne(
        { _id: event._id, status: DomainEventStatus.PROCESSING },
        {
          $set: {
            status: deadLetter
              ? DomainEventStatus.DEAD_LETTER
              : DomainEventStatus.FAILED,
            attempts,
            lastFailureCode: failureCode,
            availableAt: new Date(
              Date.now() + Math.min(60000, 2 ** attempts * 1000),
            ),
          },
          $unset: { lockedUntil: 1 },
        },
      );
      this.logger.warn({
        eventId: event.eventId,
        eventName: event.name,
        attempts,
        failureCode,
        deadLetter,
      });
    }
  }
}
