export enum RewardTransactionType {
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  LESSON_COMPLETED = 'LESSON_COMPLETED',
  QUIZ_PASSED = 'QUIZ_PASSED',
  CHALLENGE_COMPLETED = 'CHALLENGE_COMPLETED',
  DAILY_STREAK = 'DAILY_STREAK',
  BADGE_EARNED = 'BADGE_EARNED',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
  REVERSAL = 'REVERSAL',
}

export enum BadgeCriteriaType {
  VERIFICATION_COUNT = 'VERIFICATION_COUNT',
  LESSON_COUNT = 'LESSON_COUNT',
  QUIZ_SCORE = 'QUIZ_SCORE',
  CHALLENGE_STREAK = 'CHALLENGE_STREAK',
  DAILY_STREAK = 'DAILY_STREAK',
  REPORT_FEEDBACK = 'REPORT_FEEDBACK',
  SPECIAL_EVENT = 'SPECIAL_EVENT',
}

export enum LeaderboardPeriod {
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
  ALL_TIME = 'ALL_TIME',
}
