export enum AnalyticsEventType {
  EVIDENCE_SOURCE_OPENED = 'EVIDENCE_SOURCE_OPENED',
  SIMPLE_MODE_USED = 'SIMPLE_MODE_USED',
  LEARN_MODE_USED = 'LEARN_MODE_USED',
  MIL_COACH_OPENED = 'MIL_COACH_OPENED',
  CHECK_CARD_CREATED = 'CHECK_CARD_CREATED',
  AUDIO_SUMMARY_USED = 'AUDIO_SUMMARY_USED',
  ACCESSIBILITY_FEATURE_USED = 'ACCESSIBILITY_FEATURE_USED',
  BADGE_CELEBRATION_VIEWED = 'BADGE_CELEBRATION_VIEWED',
  RANK_CELEBRATION_VIEWED = 'RANK_CELEBRATION_VIEWED',
  REPORT_LANGUAGE_CHANGED = 'REPORT_LANGUAGE_CHANGED',
}
