export enum NotificationType {
  VERIFICATION_COMPLETED = 'VERIFICATION_COMPLETED',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  REPORT_READY = 'REPORT_READY',
  BADGE_EARNED = 'BADGE_EARNED',
  LEVEL_UP = 'LEVEL_UP',
  STREAK_REMINDER = 'STREAK_REMINDER',
  DAILY_CHALLENGE = 'DAILY_CHALLENGE',
  LESSON_RECOMMENDATION = 'LESSON_RECOMMENDATION',
  SECURITY_ALERT = 'SECURITY_ALERT',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
}
export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  PUSH = 'PUSH',
}
export enum NotificationDeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  NOT_CONFIGURED = 'NOT_CONFIGURED',
  SKIPPED_PREFERENCE = 'SKIPPED_PREFERENCE',
}
