export enum UrlSourceKind {
  STANDARD_WEBPAGE = 'STANDARD_WEBPAGE',
  NEWS_ARTICLE = 'NEWS_ARTICLE',
  SOCIAL_X = 'SOCIAL_X',
  SOCIAL_OTHER = 'SOCIAL_OTHER',
  DOCUMENT = 'DOCUMENT',
  MEDIA_PAGE = 'MEDIA_PAGE',
}
