export enum VerificationSourceType {
  TEXT = 'TEXT',
  URL = 'URL',
  IMAGE = 'IMAGE',
  SCREENSHOT = 'SCREENSHOT',
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
  WHATSAPP_TEXT = 'WHATSAPP_TEXT',
  WHATSAPP_URL = 'WHATSAPP_URL',
  WHATSAPP_IMAGE = 'WHATSAPP_IMAGE',
  WHATSAPP_AUDIO = 'WHATSAPP_AUDIO',
}
