export enum EvidenceRelationship {
  SUPPORTS = 'SUPPORTS',
  CONTRADICTS = 'CONTRADICTS',
  PROVIDES_CONTEXT = 'PROVIDES_CONTEXT',
  MENTIONS_ONLY = 'MENTIONS_ONLY',
  INCONCLUSIVE = 'INCONCLUSIVE',
}

export enum EvidenceAccessStatus {
  AVAILABLE = 'AVAILABLE',
  PARTIALLY_AVAILABLE = 'PARTIALLY_AVAILABLE',
  NOT_FOUND = 'NOT_FOUND',
  BLOCKED = 'BLOCKED',
  TIMEOUT = 'TIMEOUT',
  UNSAFE_URL = 'UNSAFE_URL',
  UNSUPPORTED = 'UNSUPPORTED',
  FETCH_FAILED = 'FETCH_FAILED',
}

export enum EvidenceAuthority {
  HIGH = 'HIGH',
  MODERATE = 'MODERATE',
  UNKNOWN = 'UNKNOWN',
  INSUFFICIENT_INFORMATION = 'INSUFFICIENT_INFORMATION',
}

export enum EvidenceLineageType {
  UNIQUE = 'UNIQUE',
  DUPLICATE = 'DUPLICATE',
  SYNDICATED_CANDIDATE = 'SYNDICATED_CANDIDATE',
}
